version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /:/
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
