version: '3.8'

services:
  web:
    build: ./
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/mediafiles
    expose:
      - 1337
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: